language: node_js

node_js:
  - "stable"
  - "lts/*"

branches:
  only:
    - master
    - /^greenkeeper/.*$/

cache:
  directories:
  - node_modules

before_script:
  - "npm i -g gatsby-cli"
  - "npm install"

script:
  - gatsby build