describe('project', () => {
  it('should be accessible from the projets page', () => {
    cy.visit('/')
      .waitForRouteChange()
      .getByText(/Projets/i)
      .click()
      .waitForRouteChange()
      .assertRoute('/projets')
  })
  it('should contain title, description', () => {
    cy.visit('/projets')
      .waitForRouteChange()
      .getByText(/Projets/i)
      .getByText(/04.12.2017/i)
      .getByText(/Hi! I hope you like this starter and enjoy working with it./i)
      .getByAltText(/isak-dalsfelt/i)
  })
  it('should have working previous pagination link', () => {
    cy.visit('/projet/construction-du-site')
      .waitForRouteChange()
      .getByText(/Construction du site/i)
      .click()
      .waitForRouteChange()
      .assertRoute('/projet/construction-du-site/')
  })
  it('should have working next pagination link', () => {
    cy.visit('/projet/collection-css')
      .waitForRouteChange()
      .getByText(/Collection CSS/i)
      .click()
      .waitForRouteChange()
      .assertRoute('/projet/collection-css')
  })
})
